# Generated by Django 2.2.12 on 2021-03-11 11:26

import analisis_sentimen.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=25)),
                ('tipe_data', models.CharField(max_length=25)),
                ('tweets', djongo.models.fields.ArrayField(model_container=analisis_sentimen.models.Tweets)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
