# Generated by Django 2.2.12 on 2021-03-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_sentimen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasets',
            name='keyword',
            field=models.CharField(max_length=50),
        ),
    ]
